<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latestMajor</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Watson" Version="7.0.14" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BotFramework\BotFramework.csproj" />
  </ItemGroup>

</Project>
