name: Build & test

on:
  push:
    paths:
      - 'TGBotFramework/BotFramework/**'
      - 'TGBotFramework/BotFramework.Tests/**'
  pull_request:
    types:
      – ready_for_review
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x.x
        
    - name: Restore dependencies
      run: |
        cd TGBotFramework/BotFramework
        dotnet restore
      
    - name: Build
      run: |
        cd TGBotFramework/BotFramework
        dotnet build --no-restore
      
    - name: Test
      run: |
        cd TGBotFramework/BotFramework.Tests
        dotnet test --no-build --verbosity normal
