name: .NET

on:
  [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build with dotnet
      env:
        NugetAPIKey: ${{ secrets.NugetAPIKey }}
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      run: |
        cd build 
        bash build.sh
